//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Actions"",
    ""maps"": [
        {
            ""name"": ""MyMap"",
            ""id"": ""cd4c2664-f265-415d-accd-f857856dc25a"",
            ""actions"": [
                {
                    ""name"": ""ZQSD Movement"",
                    ""type"": ""Value"",
                    ""id"": ""590be180-188b-4b74-bb51-b5f28cea6384"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Head Movement"",
                    ""type"": ""Value"",
                    ""id"": ""7f2465cb-63be-4cf8-808d-8638a3c837de"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6f2d1517-8c71-40d1-a6e8-f0d9765a794a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""a5414500-f630-4aff-98af-987802ea1f04"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ae84685a-a9fd-4b0b-aa93-5b59cd692017"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZQSD Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""62881ac4-a926-44ec-b1fd-19e4e0ce57ae"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZQSD Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8038902d-86a3-4137-8c86-0a38e8635fb5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZQSD Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4a2fdc06-94cc-459f-abe2-d058ef7cd1e4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZQSD Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a8313975-7794-4697-b728-0759a97af46a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZQSD Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fa13e974-6d14-44b6-8006-a698cebd2de2"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Head Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e232085a-cf07-459c-be9b-682834e02055"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a97aca8d-69d9-4418-b305-fd4ce9c55a23"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MyMap
        m_MyMap = asset.FindActionMap("MyMap", throwIfNotFound: true);
        m_MyMap_ZQSDMovement = m_MyMap.FindAction("ZQSD Movement", throwIfNotFound: true);
        m_MyMap_HeadMovement = m_MyMap.FindAction("Head Movement", throwIfNotFound: true);
        m_MyMap_Jump = m_MyMap.FindAction("Jump", throwIfNotFound: true);
        m_MyMap_Fire = m_MyMap.FindAction("Fire", throwIfNotFound: true);
    }

    ~@InputActions()
    {
        UnityEngine.Debug.Assert(!m_MyMap.enabled, "This will cause a leak and performance issues, InputActions.MyMap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MyMap
    private readonly InputActionMap m_MyMap;
    private List<IMyMapActions> m_MyMapActionsCallbackInterfaces = new List<IMyMapActions>();
    private readonly InputAction m_MyMap_ZQSDMovement;
    private readonly InputAction m_MyMap_HeadMovement;
    private readonly InputAction m_MyMap_Jump;
    private readonly InputAction m_MyMap_Fire;
    public struct MyMapActions
    {
        private @InputActions m_Wrapper;
        public MyMapActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ZQSDMovement => m_Wrapper.m_MyMap_ZQSDMovement;
        public InputAction @HeadMovement => m_Wrapper.m_MyMap_HeadMovement;
        public InputAction @Jump => m_Wrapper.m_MyMap_Jump;
        public InputAction @Fire => m_Wrapper.m_MyMap_Fire;
        public InputActionMap Get() { return m_Wrapper.m_MyMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MyMapActions set) { return set.Get(); }
        public void AddCallbacks(IMyMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MyMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MyMapActionsCallbackInterfaces.Add(instance);
            @ZQSDMovement.started += instance.OnZQSDMovement;
            @ZQSDMovement.performed += instance.OnZQSDMovement;
            @ZQSDMovement.canceled += instance.OnZQSDMovement;
            @HeadMovement.started += instance.OnHeadMovement;
            @HeadMovement.performed += instance.OnHeadMovement;
            @HeadMovement.canceled += instance.OnHeadMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
        }

        private void UnregisterCallbacks(IMyMapActions instance)
        {
            @ZQSDMovement.started -= instance.OnZQSDMovement;
            @ZQSDMovement.performed -= instance.OnZQSDMovement;
            @ZQSDMovement.canceled -= instance.OnZQSDMovement;
            @HeadMovement.started -= instance.OnHeadMovement;
            @HeadMovement.performed -= instance.OnHeadMovement;
            @HeadMovement.canceled -= instance.OnHeadMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
        }

        public void RemoveCallbacks(IMyMapActions instance)
        {
            if (m_Wrapper.m_MyMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMyMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MyMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MyMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MyMapActions @MyMap => new MyMapActions(this);
    public interface IMyMapActions
    {
        void OnZQSDMovement(InputAction.CallbackContext context);
        void OnHeadMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
    }
}
